// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkwgzfayobukangvhlha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrd2d6ZmF5b2J1a2FuZ3ZobGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTQ4ODEsImV4cCI6MjA2NzczMDg4MX0.y8Kgbm3QhJGV8sj69pIdFuV8VADn0_uhkmnYDc3rlB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});